todo_website/todo/urls.py
from django.urls import path
from .views import TodoListView, TodoDeleteView, create


urlpatterns = [
    path('', TodoListView.as_view(), name='todo-home'),
    path('create/', create, name='todo-create'),
    path('delete/<int:pk>/', TodoDeleteView.as_view(), name='todo-delete'),
]

todo_website/todo_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls'))
]

todo_website/todo/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
class Todo(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('todo-home', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

todo_website/todo/forms.py
from django.forms.models import ModelForm
from .models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'description']

todo_website/todo/views.py
from django.views import generic
from django.shortcuts import render, redirect
from .models import Todo
from .forms import TodoForm


# Create your views here.
class TodoListView(generic.ListView):
    model = Todo
    template_name = 'todo/home.html'


def create(request):
    form = TodoForm()
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo-home')

    context = {'form': form}
    return render(request, 'todo/create.html', context)


class TodoDeleteView(generic.DeleteView):
    model = Todo
    success_url = '/'

todo_website/todo/templates/todo/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Todo Website</title>
  </head>
  <body>
    {% block content %}
        
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todo_website/todo/templates/todo/create.html
{% extends 'todo/base.html' %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>
{% endblock content %}

todo_website/todo/templates/todo/home.html
{% extends 'todo/base.html' %}

{% block content %}
<section class="vh-100" style="background-color: #e2d5de;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">

                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-5">

                        <h6 class="mb-3">Awesome Todo List</h6>

                        <form class="d-flex justify-content-center align-items-center mb-4">
                            <div class="form-outline flex-fill">
                                <input type="text" id="form3" class="form-control form-control-lg"/>
                                <label class="form-label" for="form3">What do you need to do today?</label>
                            </div>
                            <a href="{% url 'todo-create' %}" class="btn btn-primary btn-lg ms-2">Add</a>

                        </form>

                        {% for todo in todo_list %}
                        <ul class="list-group mb-0">
                            <li
                                    class="list-group-item d-flex justify-content-between align-items-center border-start-0 border-top-0 border-end-0 border-bottom rounded-0 mb-2">
                                <div class="d-flex align-items-center">
                                    <input class="form-check-input me-2" type="checkbox" value="" aria-label="..."/>
                                    {{ todo.title }}

                                </div>
                                <a href="{% url 'todo-delete' todo.id %}" class="text-right text-danger">Delete</a>
                            </li>
                        </ul>
                        {% endfor %}

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
{% endblock content %}

todo_website/todo/templates/todo/todo_confirm_delete.html
{% extends 'todo/base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <h2>Are you sure you want to delete {{ todo.title }}?</h2>
        <input type="submit" value="Confirm">
        <a href="{% url 'todo-home' %}">Cancel</a>
    </form>
{% endblock content %}